import { createContext, useContext, useState, ReactNode } from "react";

export type LanguageCode = "en" | "uz" | "ru" | "ko";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    hero_title_1: "YOUR GATEWAY TO",
    hero_title_2: "GLOBAL EDUCATION.",
    hero_subtitle: "Master IELTS, SAT, and TOPIK with the elite methodology trusted by the most ambitious students in Uzbekistan. Start your journey to the world's top universities today.",
    cta_assessment: "Apply Now",
    cta_courses: "View Courses",
    nav_courses: "Courses",
    nav_teachers: "Teachers",
    nav_roadmap: "Roadmap",
    nav_faq: "FAQ",
    apply_now: "Apply Now",
    enroll_now: "Enroll Now",
    contact_telegram: "Contact Telegram",
    curriculum_title: "CHOOSE YOUR",
    curriculum_subtitle: "EXCELLENCE.",
    teachers_title: "LEARN FROM THE",
    teachers_subtitle: "BEST.",
    roadmap_title: "THE",
    roadmap_subtitle: "SUCCESS ROADMAP.",
    footer_tagline: "Pioneering high-intensity test preparation and academic consulting in Uzbekistan.",
    roadmap_desc: "From evaluation to your dream university—we guide you every step of the way with precision and expert mentorship.",
    roadmap_phase: "Phase",
    assessment: "Assessment",
    assessment_desc: "Direct evaluation of your academic foundation and target goals.",
    strategy: "Strategy",
    strategy_desc: "Customized study plan targeting your specific University requirements.",
    execution: "Execution",
    execution_desc: "High-intensity training with native experts and certified examiners.",
    admissions: "Admissions",
    admissions_desc: "Expert consulting for your university applications and visa support.",
    faq_title: "Frequently Asked",
    faq_questions: "Questions",
    hero_badge: "Leading Prep Center in Uzbekistan",
    cta_dream: "STOP DREAMING.",
    cta_achieve: "START ACHIEVING.",
    cta_spots: "Limited spots available for the Spring intake. Your future at a top-tier global university begins here. Secure your seat today.",
    course_ielts: "IELTS Intensive",
    course_ielts_desc: "Master all 4 sections with certified examiners. 3-month high-intensity program.",
    course_sat: "SAT Advanced",
    course_sat_desc: "Target 1500+ with proprietary strategies for Math and Reading.",
    course_topik: "TOPIK Success",
    course_topik_desc: "Learn Korean Proficiency from Level 1 to 6 with native speakers.",
    hero_join: "Join Core Academy",
    footer_about: "Pioneering high-intensity test preparation and academic consulting in Uzbekistan. We empower the next generation of global leaders to secure their place in the world's most prestigious universities.",
    footer_quick_links: "Quick Links",
    footer_contact_us: "Contact Us",
    footer_address: "Jarkurgan, Surkhandarya",
    teacher_umidjon_role: "Founder & CEO",
    teacher_umidjon_bio: "Visionary leader dedicated to transforming educational standards in Uzbekistan.",
    teacher_dustyor_role: "Operations Manager",
    teacher_dustyor_bio: "Ensuring excellence in every classroom. Specialized in student success pathways.",
    teacher_elena_role: "IELTS Lead Examiner",
    teacher_elena_bio: "Certified British Council trainer. Helped 500+ students reach Band 8.0+.",
    teacher_alisher_role: "Senior SAT Math Lead",
    teacher_alisher_bio: "Masters in Applied Mathematics. Expert in shortcuts and analytical strategies.",
    teacher_james_role: "Academic Writing Coach",
    teacher_james_bio: "Harvard Extension alum. Specialized in personal statements and critical analysis.",
    teacher_zebo_role: "TOEFL & Academic English",
    teacher_zebo_bio: "Expert in formal academic structures and advanced linguistics.",
    teacher_malika_role: "DET & Linguistics Specialist",
    teacher_malika_bio: "Specialized in Duolingo English Test and phonetic comprehension.",
    teacher_sara_role: "TOPIK Level 6 Master",
    teacher_sara_bio: "Native speaker with 10+ years experience in Korean university admissions.",
    teachers_description: "Our instructors aren't just teachers; they are mentors who have mastered the exams themselves and graduated from world-class universities.",
    teachers_faculty: "Elite Faculty",
    faq_q1: "How long is the average preparation course?",
    faq_a1: "Most intensive courses last between 3 to 4 months, depending on your initial level and target score.",
    faq_q2: "Do you offer online classes?",
    faq_a2: "Yes, we have a premium hybrid model that combines physical intensive workshops with digital learning resources accessible anywhere.",
    faq_q3: "Can I get a scholarship based on my results?",
    faq_a3: "Absolutely. Our academic consulting team specializes in identifying and applying for full-ride scholarships globally.",
    apply_title: "Secure Your",
    apply_subtitle: "Elite Future.",
    apply_desc: "Join the ranks of students securing Ivy League admissions. Our experts will contact you within 24 hours.",
    apply_field_name: "Full Name",
    apply_field_tg: "Telegram Username",
    apply_field_phone: "Phone Number",
    apply_field_course: "Select Your Path",
    apply_submit: "Send Application",
    apply_success_title: "TRANSMISSION SUCCESSFUL",
    apply_success_desc: "Your application has been logged. An academic advisor will reach out shortly.",
    stat_students: "Success Stories",
    stat_ielts: "IELTS Mastery",
    stat_sat: "SAT Champions",
    banner_title: "FAST-TRACK ADMISSIONS",
    banner_desc: "Guaranteed structural preparation with certified native experts and global admissions advisors. Transform your scores and secure your spot today.",
    banner_btn: "Request consultation",
  },
  uz: {
    hero_title_1: "GLOBAL TA'LIMGA",
    hero_title_2: "SIZNING YO'LINGIZ.",
    hero_subtitle: "O'zbekistondagi eng shijoatli talabalar ishonadigan elita metodologiyasi bilan IELTS, SAT va TOPIKni o'zlashtiring. Bugun dunyoning eng yaxshi universitetlari sari sayohatingizni boshlang.",
    cta_assessment: "Hozir ariza topshirish",
    cta_courses: "Kurslarni ko'rish",
    nav_courses: "Kurslar",
    nav_teachers: "O'qituvchilar",
    nav_roadmap: "Yo'l xaritasi",
    nav_faq: "FAQ",
    apply_now: "Ariza topshirish",
    enroll_now: "Kursga yozilish",
    contact_telegram: "Telegram orqali bog'lanish",
    curriculum_title: "O'ZINGIZNING",
    curriculum_subtitle: "MUKAMMALLIKNI TANLANG.",
    teachers_title: "ENG YAXSHILARDAN",
    teachers_subtitle: "O'RGANING.",
    roadmap_title: "MUVAFFAQIYAT",
    roadmap_subtitle: "YO'L XARITASI.",
    footer_tagline: "O'zbekistonda yuqori intensivlikdagi testlarga tayyorgarlik va akademik konsalting bo'yicha yetakchi.",
    roadmap_desc: "Baholashdan orzuingizdagi universitetgacha — biz sizga har qadamda aniqlik va ekspert ustozligi bilan yo'l ko'rsatamiz.",
    roadmap_phase: "Bosqich",
    assessment: "Baholash",
    assessment_desc: "Akademik poydevoringiz va maqsadli natijalaringizni to'g'ridan-to'g'ri baholash.",
    strategy: "Strategiya",
    strategy_desc: "Sizning maxsus universitet talablariga mo'ljallangan strategik reja.",
    execution: "Ijro",
    execution_desc: "Mahalliy ekspertlar va sertifikatlangan imtihonchilar bilan yuqori intensiv trening.",
    admissions: "Qabul",
    admissions_desc: "Universitet hujjatlarini topshirish va viza masalari bo'yicha ekspert konsalting.",
    faq_title: "Ko'p so'raladigan",
    faq_questions: "Savollar",
    hero_badge: "O'zbekistondagi yetakchi tayyorgarlik markazi",
    cta_dream: "ORZU QILISHDAN TO'XTANG.",
    cta_achieve: "ERISHISHNI BOSHLANG.",
    cta_spots: "Bahorgi qabul uchun joylar cheklangan. Dunyo darajasidagi universitetdagi kelajagingiz shu yerdan boshlanadi.",
    course_ielts: "IELTS Intensiv",
    course_ielts_desc: "Barcha 4 bo'limni sertifikatlangan imtihonchilar bilan o'zlashtiring. 3 oylik yuqori intensiv dastur.",
    course_sat: "SAT Advanced",
    course_sat_desc: "Matematika va o'qish bo'yicha maxsus strategiyalar bilan 1500+ ballni maqsad qiling.",
    course_topik: "TOPIK Success",
    course_topik_desc: "Koreys tili mahoratini mahalliy mutaxassislar bilan 1-dan 6-darajagacha o'rganing.",
    hero_join: "Core Academy-ga qo'shiling",
    footer_about: "O'zbekistonda yuqori intensivlikdagi testlarga tayyorgarlik va akademik konsalting bo'yicha yetakchi. Biz kelajakdagi global liderlarga dunyoning eng nufuzli universitetlaridan joy olishga yordam beramiz.",
    text_is_submitting: "Yuborilmoqda...",
    footer_quick_links: "Tezkor havolalar",
    footer_contact_us: "Bog'lanish",
    footer_address: "Jarqo'rg'on, Surxondaryo",
    teacher_umidjon_role: "Asoschisi va CEO",
    teacher_umidjon_bio: "O'zbekistondagi ta'lim standartlarini transformatsiya qilishga bag'ishlangan vizioner lider.",
    teacher_dustyor_role: "Operatsion menejer",
    teacher_dustyor_bio: "Har bir sinfda mukammallikni ta'minlaydi. Operatsion samaradorlik bo'yicha ixtisoslashgan.",
    teacher_elena_role: "IELTS yetakchi imtihonchisi",
    teacher_elena_bio: "Sertifikatlangan British Council treneri. 500 dan ortiq talabaga yordam bergan.",
    teacher_alisher_role: "Katta SAT Matematika rahbari",
    teacher_alisher_bio: "Qisqa yo'llar va tahliliy strategiyalar bo'yicha ekspert.",
    teacher_james_role: "Akademik yozish bo'yicha murabbiy",
    teacher_james_bio: "Garvard bitiruvchisi. Shaxsiy bayonotlar va tanqidiy tahlilga ixtisoslashgan.",
    teacher_zebo_role: "TOEFL va Akademik Ingliz tili",
    teacher_zebo_bio: "Rasmiy akademik tuzilmalar va ilg'or tilshunoslik bo'yicha ekspert.",
    teacher_malika_role: "DET va tilshunoslik mutaxassisi",
    teacher_malika_bio: "Duolingo ingliz tili testi va fonetik tushunishga ixtisoslashgan.",
    teacher_sara_role: "TOPIK Level 6 ustasi",
    teacher_sara_bio: "Koreya universitetlariga qabul qilish bo'yicha 10 yildan ortiq tajribaga ega mahalliy ma'ruzachi.",
    teachers_description: "Bizning o'qituvchilarimiz shunchaki o'qituvchi emas; ular imtihonlarni o'zlari muvaffaqiyatli topshirgan ustozlordir.",
    teachers_faculty: "Elita Fakulteti",
    faq_q1: "Tayyorgarlik kursi qancha davom etadi?",
    faq_a1: "Ko'pgina intensiv kurslar 3 oydan 4 oygacha davom etadi.",
    faq_q2: "Onlayn darslar bormi?",
    faq_a2: "Ha, bizda gibrid o'qitish modeli mavjud.",
    faq_q3: "Grant yutib olish mumkinmi?",
    faq_a3: "Albatta. Bizning jamoamiz xalqaro grantlar bo'yicha ixtisoslashgan.",
    apply_title: "Kelajagingizni",
    apply_subtitle: "Ta'minlang.",
    apply_desc: "Ivy League universitetlariga qabul qilinayotgan talabalar safiga qo'shiling. Ekspertlarimiz 24 soat ichida bog'lanishadi.",
    apply_field_name: "Ism sharifingiz",
    apply_field_tg: "Telegram foydalanuvchi nomi",
    apply_field_phone: "Telefon raqami",
    apply_field_course: "Yo'nalishni tanlang",
    apply_submit: "Arizani yuborish",
    apply_success_title: "ARIZA MUVAFFAQIYATLI YUBORILDI",
    apply_success_desc: "Sizning arizangiz qayd etildi. Tez orada akademik maslahatchi siz bilan bog'lanadi.",
    stat_students: "Muvaffaqiyatlar",
    stat_ielts: "IELTS natijalari",
    stat_sat: "SAT chempionlari",
    banner_title: "TEZKOR UNIVERSITETGA QABUL DASTURI",
    banner_desc: "Sertifikatlangan mahalliy mutaxassislar va xalqaro universitet maslahatchilari bilan kafolatlangan tayyorgarlik. Arizangizni hozir yuboring.",
    banner_btn: "Bepul maslahat olish",
  },
  ru: {
    hero_title_1: "ВАШ ПУТЬ К",
    hero_title_2: "ГЛОБАЛЬНОМУ ОБРАЗОВАНИЮ.",
    hero_subtitle: "Освойте IELTS, SAT и TOPIK с помощью элитной методологии, которой доверяют самые амбициозные студенты Узбекистана. Начните свой путь в лучшие университеты мира сегодня.",
    cta_assessment: "Подать заявку сейчас",
    cta_courses: "Посмотреть курсы",
    nav_courses: "Курсы",
    nav_teachers: "Учителя",
    nav_roadmap: "Дорожная карта",
    nav_faq: "FAQ",
    apply_now: "Подать заявку",
    enroll_now: "Записаться",
    contact_telegram: "Связаться в Telegram",
    curriculum_title: "ВЫБЕРИТЕ СВОЕ",
    curriculum_subtitle: "СОВЕРШЕНСТВО.",
    teachers_title: "УЧИТЕСЬ У",
    teachers_subtitle: "ЛУЧШИХ.",
    roadmap_title: "ДОРОЖНАЯ КАРТА",
    roadmap_subtitle: "УСПЕХА.",
    footer_tagline: "Ведущая компания в Узбекистане по высокоинтенсивной подготовке к тестам и академическому консультированию.",
    roadmap_desc: "От оценки до университета вашей мечты — мы ведем вас на каждом шагу с точностью и экспертным наставничеством.",
    roadmap_phase: "Фаза",
    assessment: "Оценка",
    assessment_desc: "Прямая оценка вашей академической базы и целевых показателей.",
    strategy: "Стратегия",
    strategy_desc: "Индивидуальный план обучения, ориентированный на требования вашего университета.",
    execution: "Выполнение",
    execution_desc: "Высокоинтенсивное обучение с местными экспертами и сертифицированными экзаменаторами.",
    admissions: "Поступление",
    admissions_desc: "Экспертное консультирование по подаче документов в университет и визовая поддержка.",
    faq_title: "Часто задаваемые",
    faq_questions: "Вопросы",
    hero_badge: "Ведущий учебный центр в Узбекистане",
    cta_dream: "ХВАТИТ МЕЧТАТЬ.",
    cta_achieve: "НАЧНИТЕ ДОСТИГАТЬ.",
    cta_spots: "Количество мест ограничено. Ваше будущее начинается здесь.",
    course_ielts: "IELTS Интенсив",
    course_ielts_desc: "Освойте все 4 раздела с сертифицированными экзаменаторами. 3-месячная интенсивная программа.",
    course_sat: "SAT Advanced",
    course_sat_desc: "Цель 1500+ с использованием уникальных стратегий.",
    course_topik: "TOPIK Success",
    course_topik_desc: "Изучайте корейский язык от уровня 1 до 6 с носителями языка.",
    hero_join: "Присоединяйтесь к Core Academy",
    footer_about: "Ведущая компания в Узбекистане по подготовке к тестам. Мы помогаем будущим лидерам занять места в престижных университетах мира.",
    footer_quick_links: "Быстрые ссылки",
    footer_contact_us: "Свяжитесь с нами",
    footer_address: "Джаркурган, Сурхандарья",
    teacher_umidjon_role: "Основатель и CEO",
    teacher_umidjon_bio: "Дальновидный лидер, стремящийся к трансформации образовательных стандартов.",
    teacher_dustyor_role: "Операционный менеджер",
    teacher_dustyor_bio: "Обеспечение совершенства в каждом классе.",
    teacher_elena_role: "Ведущий экзаменатор IELTS",
    teacher_elena_bio: "Сер티фицированный тренер British Council. Помогла более чем 500 студентам.",
    teacher_alisher_role: "Ведущий преподаватель SAT Math",
    teacher_alisher_bio: "Эксперт по коротким путям решения задач и аналитическим стратегиям.",
    teacher_james_role: "Тренер по академическому письму",
    teacher_james_bio: "Выпускник Гарварда. Специализируется на мотивационных письмах.",
    teacher_zebo_role: "TOEFL и академический английский",
    teacher_zebo_bio: "Эксперт по формальным академическим структурам и продвинутой лингвистике.",
    teacher_malika_role: "Специалист по DET и лингвистике",
    teacher_malika_bio: "Специализируется на Duolingo English Test и фонетическом понимании.",
    teacher_sara_role: "Мастер TOPIK уровня 6",
    teacher_sara_bio: "Носитель языка с более чем 10-летним опытом академического консультирования.",
    teachers_description: "Наши инструкторы — это наставники, которые сами освоили экзамены и закончили университеты мирового уровня.",
    teachers_faculty: "Элитный Факультет",
    faq_q1: "Как долго длится курс?",
    faq_a1: "Большинство интенсивных курсов длятся от 3 до 4 месяцев.",
    faq_q2: "Есть ли онлайн-занятия?",
    faq_a2: "Да, у нас есть ги브ридная модель обучения.",
    faq_q3: "Можно ли получить стипендию?",
    faq_a3: "Безусловно. Наша команда специализируется на поиске полных стипендий.",
    apply_title: "Обеспечьте свое",
    apply_subtitle: "Элитное Будущее.",
    apply_desc: "Присоединяйтесь к студентам, поступающим в Лигу Плюща. Наши эксперты свяжутся с вами в течение 24 часов.",
    apply_field_name: "Ваше Имя",
    apply_field_tg: "Username в Telegram",
    apply_field_phone: "Номер телефона",
    apply_field_course: "Выберите Направление",
    apply_submit: "Отправить Заявку",
    apply_success_title: "ЗАЯВКА УСПЕШНО ОТПРАВЛЕНА",
    apply_success_desc: "Ваша заявка зарегистрирована. Скоро с вами свяжется академический консультант.",
    stat_students: "Успешные кейсы",
    stat_ielts: "Средний балл IELTS",
    stat_sat: "Результаты SAT",
    banner_title: "БЫСТРЫЙ ПУТЬ К ПОСТУПЛЕНИЮ",
    banner_desc: "Гарантированная подготовка с носителями языка и специалистами по международному поступлению. Начните свой путь к успеху сегодня.",
    banner_btn: "Получить консультацию",
  },
  ko: {
    hero_title_1: "글로벌 교육으로 가는",
    hero_title_2: "당신의 관문.",
    hero_subtitle: "우즈베키스탄에서 가장 야심 찬 학생들이 신뢰하는 엘리트 방법론으로 IELTS, SAT, TOPIK을 마스터하세요. 오늘 세계 최고의 대학을 향한 여정을 시작하세요.",
    cta_assessment: "지금 지원하기",
    cta_courses: "코스 보기",
    nav_courses: "코스",
    nav_teachers: "교사",
    nav_roadmap: "로드맵",
    nav_faq: "FAQ",
    apply_now: "지금 신청하기",
    enroll_now: "등록하기",
    contact_telegram: "텔레그램 문의",
    curriculum_title: "당신의",
    curriculum_subtitle: "탁월함을 선택하세요.",
    teachers_title: "최고에게",
    teachers_subtitle: "배우세요.",
    roadmap_title: "성공",
    roadmap_subtitle: "로드맵.",
    footer_tagline: "우즈베키스탄에서 고강도 시험 준비 및 학업 컨설팅을 선도하고 있습니다.",
    roadmap_desc: "평가부터 꿈의 대학까지-정밀하고 전문가적인 멘토링으로 모든 단계를 안내합니다.",
    roadmap_phase: "단계",
    assessment: "평가",
    assessment_desc: "학업 기초 및 목표에 대한 직접적인 평가.",
    strategy: "전략",
    strategy_desc: "특정 대학 요구 사항을 목표로 하는 맞춤형 학습 계획.",
    execution: "실행",
    execution_desc: "원어민 전문가 및 공인 시험관과 함께하는 고강도 교육.",
    admissions: "입학",
    admissions_desc: "대학 지원 및 비자 지원을 위한 전문가 컨설팅.",
    faq_title: "자주 묻는",
    faq_questions: "질문",
    hero_badge: "우즈베키스탄 최고의 시험 준비 센터",
    cta_dream: "꿈만 꾸지 마세요.",
    cta_achieve: "성취를 시작하세요.",
    cta_spots: "모집 인원이 제한되어 있습니다. 세계적인 대학에서의 미래가 여기서 시작됩니다.",
    course_ielts: "IELTS 집중반",
    course_ielts_desc: "공인 시험관과 함께 4개 모든 영역을 마스터하세요. 3개월 고강도 프로그램.",
    course_sat: "SAT 심화반",
    course_sat_desc: "수학 및 독해를 위한 독자적인 전략으로 1500점 이상을 목표로 합니다.",
    course_topik: "TOPIK 성공반",
    course_topik_desc: "원어민 강사와 함께 한국어 능력을 1급에서 6급까지 배우세요.",
    hero_join: "Core Academy와 함께하세요",
    footer_about: "우즈베키스탄에서 고강도 시험 준비 및 학업 컨설팅을 선도하고 있습니다. 우리는 차세대 글로벌 리더들이 세계 최고의 대학에 합격할 수 있도록 돕습니다.",
    footer_quick_links: "빠른 링크",
    footer_contact_us: "문의하기",
    footer_address: "자르쿠르간, 수르칸다리야",
    teacher_umidjon_role: "설립자 및 CEO",
    teacher_umidjon_bio: "우즈베키스탄의 교육 표준을 변화시키는 데 전념하는 선구적인 리더입니다.",
    teacher_dustyor_role: "운영 매니저",
    teacher_dustyor_bio: "모든 강의실에서 우수성을 보장합니다.",
    teacher_elena_role: "IELTS 수석 시험관",
    teacher_elena_bio: "공인 브리티시 카운실 트레이너입니다. 500명 이상의 학생이 Band 8.0 이상을 달성하도록 도왔습니다.",
    teacher_alisher_role: "SAT 수학 수석 팀장",
    teacher_alisher_bio: "응용 수학 석사. 단축키 및 분석 전략 전문가.",
    teacher_james_role: "아카데믹 라이팅 코치",
    teacher_james_bio: "하버드 출신. 자기소개서 및 비판적 분석 전문.",
    teacher_zebo_role: "TOEFL 및 아카데믹 영어",
    teacher_zebo_bio: "공식적인 학술 구조 및 고급 언어학 전문가.",
    teacher_malika_role: "DET 및 언어학 전문가",
    teacher_malika_bio: "듀오링고 영어 시험 및 음성 이해 전문.",
    teacher_sara_role: "TOPIK 6급 마스터",
    teacher_sara_bio: "한국 대학 입학 분야에서 10년 이상의 경력을 가진 원어민입니다.",
    teachers_description: "우리의 강사진은 시험을 직접 마스터하고 세계적 수준의 대학을 졸업한 멘토들입니다.",
    teachers_faculty: "엘리트 교수진",
    faq_q1: "준비 과정은 얼마나 걸리나요?",
    faq_a1: "대부분의 집중 과정은 3~4개월 동안 진행됩니다.",
    faq_q2: "온라인 강의를 제공하나요?",
    faq_a2: "네, 프리미엄 하이브리드 모델을 운영하고 있습니다.",
    faq_q3: "장학금을 받을 수 있나요?",
    faq_a3: "물론입니다. 학업 컨설팅 팀은 전 세계 장학금을 지원하는 데 특화되어 있습니다.",
    apply_title: "당신의 엘리트",
    apply_subtitle: "미래를 보장하세요.",
    apply_desc: "아이비리그 대학에 합격하는 학생들의 대열에 합류하세요. 전문가가 24시간 이내에 연락드립니다.",
    apply_field_name: "성함",
    apply_field_tg: "텔레그램 아이디",
    apply_field_phone: "전화번호",
    apply_field_course: "경로 선택",
    apply_submit: "지원서 제출",
    apply_success_title: "전송 성공",
    apply_success_desc: "지원서가 등록되었습니다. 곧 학업 상담원이 연락드릴 것입니다.",
    stat_students: "성공 사례",
    stat_ielts: "평균 IELTS 점수",
    stat_sat: "SAT 성과",
    banner_title: "대학 입학 속성 프로그램",
    banner_desc: "인증된 원어민 전문가 및 글로벌 입학 지원 어드바이저와 함께하는 우수한 시험 대비 학습 전략.",
    banner_btn: "상담 요청하기",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
